const CartActionTypes = {
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  UPDATE_ITEM_STATUS: 'UPDATE_ITEM_STATUS',
  GET_ALL_ORDER: 'GET_ALL_ORDER',
  CART_ERROR: 'CART_ERROR'
};

export default CartActionTypes;
